In [1]:
!pip install pyspark
!pip install pyarrow
!pip install -q findspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.7/dist-packages (3.1.1)
Requirement already satisfied: py4j==0.10.9 in /usr/local/lib/python3.7/dist-packages (from pyspark) (0.10.9)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (3.0.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.7/dist-packages (from pyarrow) (1.19.5)

In [2]:
from pyspark.sql import SparkSession

In [3]:
spark=SparkSession.builder.appName("ops").getOrCreate()

In [4]:
df=spark.read.csv("/content/appl_stock.csv",inferSchema=True,header=True)

In [5]:
df.printSchema()

root
 |-- Date: string (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [6]:
df.show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [7]:
df.filter("Close>500").show()

+----------+------------------+------------------+------------------+------------------+---------+-----------------+
|      Date|              Open|              High|               Low|             Close|   Volume|        Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+-----------------+
|2012-02-13|        499.529991|503.83000899999996|497.08998899999995|502.60002099999997|129304000|        65.116633|
|2012-02-14|        504.659988|         509.56002|        502.000008|        509.459991|115099600|        66.005408|
|2012-02-16|        491.500008|        504.890007|         486.62999|502.20999900000004|236138000|        65.066102|
|2012-02-17|        503.109993|507.77002000000005|        500.299995|         502.12001|133951300|        65.054443|
|2012-02-21|506.88001299999996|        514.850021|504.12000300000005|        514.850021|151398800|        66.703738|
|2012-02-22|        513.079994|        515.489983|509.07002300000005|        513.039993|120825600|66.46923100000001|
|2012-02-23|        515.079987|        517.830009|        509.499992| 516.3899769999999|142006900|        66.903253|
|2012-02-24| 519.6699980000001|        522.899979| 518.6400150000001| 522.4099809999999|103768000|        67.683203|
|2012-02-27|        521.309982|             528.5| 516.2800139999999|        525.760017|136895500|        68.117232|
|2012-02-28|        527.960014|        535.410011|        525.850006|        535.410011|150096800|69.36748100000001|
|2012-02-29| 541.5600049999999| 547.6100230000001|        535.700005|        542.440025|238002800|        70.278286|
|2012-03-01|        548.169983|        548.209984| 538.7699809999999| 544.4699780000001|170817500|        70.541286|
|2012-03-02|        544.240013|        546.800018|        542.519974|        545.180008|107928100|        70.633277|
|2012-03-05|        545.420013|         547.47998|        526.000023| 533.1600269999999|202281100|        69.075974|
|2012-03-06|        523.659996|        533.690025| 516.2199860000001|        530.259987|202559700|68.70024599999999|
|2012-03-07| 536.8000030000001|        537.779999|        523.299988| 530.6900099999999|199630200|68.75595899999999|
|2012-03-08| 534.6899950000001|        542.989998|        532.120003|        541.989975|129114300|        70.219978|
|2012-03-09|        544.209999|        547.740013|        543.110001|        545.170021|104729800|70.63198299999999|
|2012-03-12| 548.9799879999999|        551.999977|        547.000023|        551.999977|101820600|        71.516869|
|2012-03-13|        557.540024|            568.18|        555.750023|        568.099998|172713800|73.60278100000001|
+----------+------------------+------------------+------------------+------------------+---------+-----------------+
only showing top 20 rows

In [8]:
df.filter("Close>500").select("Open").show()

+------------------+
|              Open|
+------------------+
|        499.529991|
|        504.659988|
|        491.500008|
|        503.109993|
|506.88001299999996|
|        513.079994|
|        515.079987|
| 519.6699980000001|
|        521.309982|
|        527.960014|
| 541.5600049999999|
|        548.169983|
|        544.240013|
|        545.420013|
|        523.659996|
| 536.8000030000001|
| 534.6899950000001|
|        544.209999|
| 548.9799879999999|
|        557.540024|
+------------------+
only showing top 20 rows

In [9]:
df.filter("Close>500").select(["Open","close"]).show()

+------------------+------------------+
|              Open|             close|
+------------------+------------------+
|        499.529991|502.60002099999997|
|        504.659988|        509.459991|
|        491.500008|502.20999900000004|
|        503.109993|         502.12001|
|506.88001299999996|        514.850021|
|        513.079994|        513.039993|
|        515.079987| 516.3899769999999|
| 519.6699980000001| 522.4099809999999|
|        521.309982|        525.760017|
|        527.960014|        535.410011|
| 541.5600049999999|        542.440025|
|        548.169983| 544.4699780000001|
|        544.240013|        545.180008|
|        545.420013| 533.1600269999999|
|        523.659996|        530.259987|
| 536.8000030000001| 530.6900099999999|
| 534.6899950000001|        541.989975|
|        544.209999|        545.170021|
| 548.9799879999999|        551.999977|
|        557.540024|        568.099998|
+------------------+------------------+
only showing top 20 rows

In [10]:
df.filter(df["close"]<500).show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [11]:
df.filter(df["close"]>500).select(["high","low"]).show()

+------------------+------------------+
|              high|               low|
+------------------+------------------+
|503.83000899999996|497.08998899999995|
|         509.56002|        502.000008|
|        504.890007|         486.62999|
|507.77002000000005|        500.299995|
|        514.850021|504.12000300000005|
|        515.489983|509.07002300000005|
|        517.830009|        509.499992|
|        522.899979| 518.6400150000001|
|             528.5| 516.2800139999999|
|        535.410011|        525.850006|
| 547.6100230000001|        535.700005|
|        548.209984| 538.7699809999999|
|        546.800018|        542.519974|
|         547.47998|        526.000023|
|        533.690025| 516.2199860000001|
|        537.779999|        523.299988|
|        542.989998|        532.120003|
|        547.740013|        543.110001|
|        551.999977|        547.000023|
|            568.18|        555.750023|
+------------------+------------------+
only showing top 20 rows

In [12]:
df.filter( (df['close']<200) & (df['open']>200) ).show()

+----------+------------------+----------+----------+----------+---------+------------------+
|      Date|              Open|      High|       Low|     Close|   Volume|         Adj Close|
+----------+------------------+----------+----------+----------+---------+------------------+
|2010-01-22|206.78000600000001|207.499996|    197.16|    197.75|220441900|         25.620401|
|2010-01-28|        204.930004|205.500004|198.699995|199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|202.199995|190.250002|192.060003|311488100|         24.883208|
+----------+------------------+----------+----------+----------+---------+------------------+

In [13]:
df.filter( (df['close']<200) & ~(df['open']>200) ).show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
|2010-02-02|        195.909998|        196.319994|193.37999299999998|        195.859997|174585600|25.375532999999997|
|2010-02-03|        195.169994|        200.200003|        194.420004|        199.229994|153832000|25.812148999999998|
|2010-02-04|        196.730003|        198.370001|        191.570005|        192.050003|189413000|         24.881912|
|2010-02-05|192.63000300000002|             196.0|        190.850002|        195.460001|212576700|25.323710000000002|
|2010-02-08|        195.690006|197.88000300000002|        193.999994|194.11999699999998|119567700|           25.1501|
|2010-02-09|        196.419996|        197.499994|        194.749998|196.19000400000002|158221700|         25.418289|
|2010-02-10|        195.889997|             196.6|            194.26|195.12000700000002| 92590400|          25.27966|
|2010-02-11|        194.880001|        199.750006|194.05999599999998|        198.669994|137586400|         25.739595|
|2010-02-23|        199.999998|        201.330002|        195.709993|        197.059998|143773700|         25.531005|
|2014-06-09|         92.699997|         93.879997|             91.75|         93.699997| 75415000|         88.906324|
|2014-06-10|         94.730003|         95.050003|             93.57|             94.25| 62777000|         89.428189|
|2014-06-11|         94.129997|         94.760002|         93.470001|         93.860001| 45681000|         89.058142|
|2014-06-12|         94.040001|         94.120003|         91.900002|         92.290001| 54749000|         87.568463|
|2014-06-13|         92.199997|         92.440002|         90.879997|         91.279999| 54525000|         86.610132|
|2014-06-16|         91.510002|             92.75|         91.449997|         92.199997| 35561000|         87.483064|
|2014-06-17|         92.309998|         92.699997|         91.800003| 92.08000200000001| 29726000| 87.36920699999999|
|2014-06-18|         92.269997|         92.290001|         91.349998|             92.18| 33514000|          87.46409|
|2014-06-19|         92.290001|         92.300003|         91.339996|         91.860001| 35528000|         87.160461|
|2014-06-20|         91.849998|         92.550003|         90.900002|         90.910004|100898000|         86.259066|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [14]:
result=df.filter(df['low']==197.16).collect()

In [15]:
result

[Row(Date='2010-01-22', Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)]

In [16]:
row=result[0]

In [17]:
row.asDict()

{'Adj Close': 25.620401,
 'Close': 197.75,
 'Date': '2010-01-22',
 'High': 207.499996,
 'Low': 197.16,
 'Open': 206.78000600000001,
 'Volume': 220441900}

In [18]:
row.asDict()["Date"]

'2010-01-22'